# A comma-separated list of supported validation types. Values need to be reflected in properties validator.typeLabel, validator.schemaFile, validator.schematronFolder.
validator.type = v3.0.0
# The description to show for the different validator types. These are defined in properties such as validator.typeLabel.TYPE.
validator.typeLabel.v3.0.0 = MLDCAT-AP version 3.0.0
# The SHACL shapes are remotely loaded.
validator.shaclFile.v3.0.0 = shapes/srm-SHACL.ttl
# The default report syntax (mime type) if none is requested.
validator.defaultReportSyntax = application/ld+json
# Title presented on the web UI.
validator.uploadTitle = MLDCAT-AP validator