# A comma-separated list of supported validation types. Values need to be reflected in properties validator.typeLabel, validator.schemaFile, validator.schematronFolder.
validator.type = v1.0.1, v1.0.0 
# The description to show for the different validator types. These are defined in properties such as validator.typeLabel.TYPE.
validator.typeLabel.v1.0.1 = srm version 1.0.1
validator.typeLabel.v1.0.0 = srm version 1.0.0
# The SHACL shapes are remotely loaded.
validator.shaclFile.v1.0.1 = shapes/srm-SHACL-1.0.1.ttl, shapes/codelist-1.0.1.ttl, shapes/ignore-requires-1.0.1.ttl
validator.shaclFile.v1.0.0 = shapes/srm-SHACL-1.0.0.ttl, shapes/codelist-1.0.0.ttl
# The default report syntax (mime type) if none is requested.
validator.defaultReportSyntax = application/ld+json
# Title presented on the web UI.
validator.uploadTitle = SRM validator

validator.loadImports.v1.0.1 = false
validator.loadImports.v1.0.0 = false