member_state: "Norway"

web_source_url: "https://sparql.fellesdatakatalog.digdir.no"
web_source_query_url: "https://sparql.fellesdatakatalog.digdir.no/?query="

enable_provenance_history: False
keep_latest_entries_provenance: 2
provenance_report_dir: SR-dev\harvester\doc\reports
provenance_report_path: SR-dev\harvester\doc\reports\norway_harvesting_report.md

fetch_query: | 
  PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  PREFIX dct: <http://purl.org/dc/terms/>
  PREFIX owl: <http://www.w3.org/2002/07/owl#>
  PREFIX modelldcatno: <https://data.norge.no/vocabulary/modelldcatno#>

  select ?s ?issued ?modified
  where {
    ?s rdf:type modelldcatno:InformationModel .
        ?s dct:issued ?issued .
        OPTIONAL {
        ?s dct:modified ?modified
    }
  } 

graphDB_host: "http://localhost:7200"
graphDB_config_file_path: "config_graphDB_repo.ttl"
graphDB_source_repo_name: "norway"
graphDB_target_repo_name: "srm"
graphDB_provenance_repo_name: "norway_prov"

transformation:
  namespaces:
    adms: "http://www.w3.org/ns/adms#"
    admsapit: "https://w3id.org/italia/onto/ADMS/"
    dct: "http://purl.org/dc/terms/"
    dcat: "http://www.w3.org/ns/dcat#"
    vann: "http://purl.org/vocab/vann/"
    foaf: "http://xmlns.com/foaf/0.1/"
    skos: "http://www.w3.org/2004/02/skos/core#"
    schema: "http://schema.org/"
    vcard: "http://www.w3.org/2006/vcard/ns#"
    m8g: "http://data.europa.eu/m8g/"
    org: "http://www.w3.org/ns/org#"
    prof: "http://www.w3.org/ns/dx/prof/"
    owl: "http://www.w3.org/2002/07/owl#"
    rdfs: "http://www.w3.org/2000/01/rdf-schema#"
    modelldcatno: "https://data.norge.no/vocabulary/modelldcatno#"
    rov: "http://www.w3.org/ns/regorg#"

validator:
  url: "http://localhost:8080/shacl/srm/api/validate"

  payload:
    validationType: "v1.0.1"
    contentSyntax: "text/turtle"
    contentToValidate: "__CONTENT__"

  headers:
    Accept: "application/ld+json"
    Content-Type: "application/json"

construct_query: |
    CONSTRUCT {
      ?s ?p ?o .
    } 
    WHERE {
      ?s ?p ?o .
      FILTER(?s = <$uri>)
    }

construct_custom_query: |
    CONSTRUCT {
      ?s ?p ?o .
    } 
    WHERE {
      ?s ?p ?o .
      FILTER(?s = <$uri>)
      FILTER(?p = <$property>)
    }

construct_classes_belonging_to_model: |
  PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  PREFIX modelldcatno: <https://data.norge.no/vocabulary/modelldcatno#>
  PREFIX dct: <http://purl.org/dc/terms/>

  CONSTRUCT {
    ?o dct:title ?title .
  }
        WHERE {
        ?s rdf:type modelldcatno:InformationModel .
        ?s modelldcatno:containsModelElement ?o .
        ?o rdf:type modelldcatno:ObjectType .
        ?o dct:title ?title
        FILTER (?s = <$uri>)
  }

construct_dcat_distribution: |
  PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  PREFIX modelldcatno: <https://data.norge.no/vocabulary/modelldcatno#>
  PREFIX dct: <http://purl.org/dc/terms/>
  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
  PREFIX dcat: <http://www.w3.org/ns/dcat#>

  CONSTRUCT {
    ?s rdfs:seeAlso ?o .
  }
        WHERE {
        ?s rdf:type modelldcatno:InformationModel .
        ?s dct:hasFormat ?format .
        ?format rdfs:seeAlso ?o .
        FILTER (?s = <$uri>)
  }
  
select_last_provenance_date_query: |
    PREFIX prov: <http://www.w3.org/ns/prov#>
    SELECT ?endTime
    WHERE {
      ?execution prov:endedAtTime ?endTime .
    }
    ORDER BY DESC(?endTime)
    LIMIT 1

delete_entries_before_re_harvesting: |
    DELETE WHERE {
      <$uri> ?p ?o .
    }
    
delete_old_entries_provenance_query: |
    PREFIX prov: <http://www.w3.org/ns/prov#>

    DELETE {
      ?s ?p ?o .
    }
    WHERE {
      ?s ?p ?o .
      
      MINUS {
        SELECT ?s
        WHERE {
          ?s prov:endedAtTime ?endTime .
        }
        ORDER BY DESC(?endTime)
        LIMIT $keep_latest
      }
    }