# SPARQL endpoint configuration
sparql:
  endpoint: "http://63.32.50.253:81/sparql"
  graph_uri: "http://semic.registry.eu"
  bypass_ssl: true

# SPARQL query for extracting download links
sparql_query: |
  prefix dct: <http://purl.org/dc/terms/>
  prefix dcat: <http://www.w3.org/ns/dcat#>
  prefix prof: <http://www.w3.org/ns/dx/prof/>
  SELECT ?s ?download
  WHERE {
    ?s a dct:Standard .
    ?s prof:hasResource ?resource .
    ?resource dct:format <http://publications.europa.eu/resource/authority/file-type/RDF_TURTLE> .
    ?resource dcat:downloadURL ?download .
  } 