# SPARQL endpoint configuration
sparql:
  sparql_query_endpoint: "http://BEPF388C13:7200/repositories/semantic-registry"
  sparql_update_endpoint: "http://BEPF388C13:7200/repositories/semantic-registry/statements" 
  graph_uri: "http://semic.registry.eu"
  bypass_ssl: true

# SPARQL query for extracting download links
sparql_query: |
  prefix dct: <http://purl.org/dc/terms/>
  prefix dcat: <http://www.w3.org/ns/dcat#>
  prefix prof: <http://www.w3.org/ns/dx/prof/>
  SELECT ?s ?download
  WHERE {
    ?s a dct:Standard .
    ?s prof:hasResource ?resource .
    ?resource dct:format <http://publications.europa.eu/resource/authority/file-type/RDF_TURTLE> .
    ?resource dcat:downloadURL ?download .
  }

lovrank_update_query: |
  PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
  INSERT DATA {{
    <{ontology_uri}> <http://example.org/LOVRank> "{lovrank_value}"^^xsd:decimal .
  }}